### ISSUE TITLE
Doesn't accept a lot of valid RAML

### ISSUE THREAD

**Issue by dolan** [danascheider/rambo#21]
If I include anything but the most basic of RAML in the file it fails on these, for example:

```
Raml::UnknownAttributeError: Unknown root key: media_type
Raml::UnknownAttributeError: Unknown root key: security_schemes
```

It wasn't hard to pare it down but I think that should at least be specified somewhere that it doesn't do the full RAML 0.8 spec.

**Comment by danascheider** [comment]
Thanks for your interest in Rambo! This gem has not yet been released for precisely this reason. Currently, although work on Rambo and its dependencies is my full-time job, I am the only person who contributes on a regular basis. I'd love to have you be part of this project if you're interested! I'd encourage you to look at the [contributor docs](https://github.com/danascheider/rambo/wiki) and browse open issues to see how you might be able to contribute. If you'd like, I can also give you some ideas and am happy to help any way I can.
