### ISSUE TITLE
Handle status codes other than 200

### ISSUE THREAD

**Issue by danascheider** [danascheider/rambo#58]
## Summary

Rambo assumes that all endpoints respond to all valid requests with a status code `200 OK`. However, this may not reflect the actual contracts being tested. Instead, Rambo should check the RAML for which status(es) are expected and then make those the expectation in the generated tests.
## Expected Behavior

If a status code other than 200 is specified in the contract, Rambo tests should verify that that is the status returned.
## Current Behavior

Rambo expects all endpoints to return status 200 in response to all correct requests, regardless of the status code(s) specified in the contract.
## Challenges

There are two challenges here. The first is handling data. Success status codes other than 200 are most likely to come from DELETE requests, POST requests that create resources, etc. Since Rambo can't currently handle apps that persist data, these requests aren't realistically being tested.

The second challenge is that of error codes. Specifically, Rambo needs to know what triggers each error. For instance, I'm not aware of a way to use RAML to specify that a 401 error is triggered by an incorrect API key, or that a 404 error is caused by the absence of a resource.
## Possible Solution

This is just a matter of adding a feature - no special problem needs to be solved as this information is already available in easy-to-consume format with `raml-rb`. It just needs a line or two added to the template, and possibly the `Method` model, to handle the information given.
## Context

Although `200 OK` is the most common success status code, others, such as `204` occur frequently as well. Enabling Rambo tests to reflect the status(es) specified in the contract will radically improve its usability.

**Comment by oscaralanpierce** [comment]
This appears to have already been implemented as of Rambo 0.7.1.
