### ISSUE TITLE
Test failing when functionality works as expected

### ISSUE THREAD

**Issue by danascheider** [danascheider/rambo#73]
## Summary

I just marked one of the tests for the `Rambo::RamlModels::Headers` class `pending` because it seems it is not testing the actual output of Rambo. Specifically, the test verifies that in the `#pretty` method, if there are multiple headers, there should be a comma after all but the last one. However, when I run this against an actual app, there end up being 2 commas. It is important that a fix be found for this, because we need our tests to clearly indicate whether the app is working.

## Expected Behavior

If the code is written such that the test passes, it looks like this:

```ruby
def pretty
  beginning = "{\n"
  ending    = "}"

  contents = headers.to_a.map {|pair|
    if headers.to_a.index(pair) == headers.length - 1
      "\t\"#{pair.first}\" => \"#{pair.last}\"\n" # No comma after last item
    else
      "\t\"#{pair.first}\" => \"#{pair.last}\",\n"
    end
  }

  "#{beginning}#{contents.join("")}#{ending}"
end
```
This code should engender a prettified output like so:
```ruby
{
  "Content-Type" => "application/json",
  "Accept" => "application/json"
}
```
## Current Behavior

The output from the above code is:
```ruby
{
  "Content-Type" => "application/json",,
  "Accept" => "application/json"
}
```
On the other hand, when I run the following code:
```ruby
def pretty
  beginning = "{\n"
  ending    = "}"

  contents = headers.to_a.map {|pair|
    "\t\"#{pair.first}\" => \"#{pair.last}\"\n"
  }

  "#{beginning}#{contents.join("")}#{ending}"
end
```
The output is:
```ruby
{
  "Content-Type" => "application/json",
  "Accept" => "application/json"
}
```
I have no idea where the comma is coming from.

## Possible Solution

I have tried troubleshooting and debugging this. At first I thought it was a typo in the code, or the Ruby version, or some similar issue, but I now don't think that's it.

## Steps to Reproduce (for bugs)

1. Replace the code in the `Rambo::RamlModels::Headers#pretty` method with the code shown under "Expected Behavior"
2. Run tests and see that they pass
3. Run against a RAML file indicating multiple headers
4. See that the generated code places 2 commas between the headers instead of 1
5. Test against the current master
6. See the test marked pending is still failing
7. Run this against the same RAML file
8. See a single comma between the headers

* Version used: rambo_ruby 0.3.0
* Operating System and version: OS X El Capitan 10.11.5
* Ruby version: 2.1.7

**Comment by zeisler** [comment]
Addressed in PR https://github.com/danascheider/rambo/pull/74
